package com.santi.turnero.whatsapp.model;

public enum WhatsAppConversationStep {
    PENDIENTE_NOMBRE_COMPLETO,
    MENU_PRINCIPAL,
    PENDIENTE_DIA,
    PENDIENTE_FRANJA,
    PENDIENTE_ALTERNATIVA_SIN_DISPONIBILIDAD,
    PENDIENTE_HORARIO,
    PENDIENTE_CONFIRMACION,
    PENDIENTE_RESPUESTA_RECORDATORIO,
    PENDIENTE_CANCELACION_TURNO,
    PENDIENTE_CONFIRMACION_CANCELACION
}
